CREATE TABLE USUARIO(
    id SERIAL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL,
    Senha VARCHAR(300) NOT NULL,
    Telefone VARCHAR(70) NOT NULL,
    Tipo VARCHAR(20) CHECK (Tipo IN ('Aluno','Coordenador','Professor', 'Empreendedor')) NOT NULL
);

CREATE TABLE SEMESTRE(
    id SERIAL PRIMARY KEY,
    Descricao CHAR(1) NOT NULL
);

CREATE TABLE STATUS_PROJETO(
    id SERIAL PRIMARY KEY,
    Descricao VARCHAR(70) NOT NULL
);

CREATE TABLE GRUPO(
    id SERIAL PRIMARY KEY,
    SEMESTRE_id integer REFERENCES SEMESTRE (id),
    Nome VARCHAR(70) NOT NULL
);

CREATE TABLE ALUNO(
    id SERIAL PRIMARY KEY,
    USUARIO_id integer REFERENCES USUARIO (id),
    GRUPO_id integer REFERENCES GRUPO (id),
    RA CHAR(13) NOT NULL,
    Nome VARCHAR(70) NOT NULL
);

CREATE TABLE HISTORICO_ALUNO(
    id SERIAL PRIMARY KEY,
    ALUNO_id integer REFERENCES ALUNO (id),
    GRUPO_id integer REFERENCES GRUPO (id)
);

CREATE TABLE DOCENTE(
    id SERIAL PRIMARY KEY,
    USUARIO_id integer REFERENCES USUARIO (id),
    Nome VARCHAR(70) NOT NULL,
    Papel VARCHAR(70) NOT NULL
);

CREATE TABLE PROJETO(
    id SERIAL PRIMARY KEY,
    DOCENTE_id integer REFERENCES DOCENTE (id),
    PAREAMENTO_id integer REFERENCES PAREAMENTO (id),
    STATUS_PROJETO_id integer REFERENCES STATUS_PROJETO (id),
    GRUPO_id integer REFERENCES GRUPO (id),
    DEMANDA_id integer REFERENCES DEMANDA (id),
    Titulo VARCHAR(70) NOT NULL,
    Descricao VARCHAR(70) NOT NULL,
    Prazo VARCHAR(70) NOT NULL,
    Tipo VARCHAR(70) NOT NULL
);

CREATE TABLE ENTREGA(
    id SERIAL PRIMARY KEY,
    PROJETO_id integer REFERENCES PROJETO (id),
    Titulo VARCHAR(70) NOT NULL,
    Descricao VARCHAR(70) NOT NULL,
    Entrega DATE NOT NULL,
    Link VARCHAR(300) NOT NULL
);

CREATE TABLE EMPREENDEDOR(
    id SERIAL PRIMARY KEY,
    USUARIO_id integer REFERENCES USUARIO (id),
    Nome VARCHAR(70) NOT NULL,
    Setor VARCHAR(70) NOT NULL,
    CNPJ CHAR(14) NOT NULL
);

CREATE TABLE COORDENADOR(
    id SERIAL PRIMARY KEY,
    USUARIO_id integer REFERENCES USUARIO (id),
    Nome VARCHAR(70) NOT NULL
);

CREATE TABLE STATUS_AVALIACAO(
    id SERIAL PRIMARY KEY,
    Descricao VARCHAR(70) NOT NULL
);

CREATE TABLE DEMANDA(
    id SERIAL PRIMARY KEY,
    STATUS_AVALIACAO_id integer REFERENCES STATUS_AVALIACAO (id),
    EMPREENDEDOR_id integer REFERENCES EMPREENDEDOR (id),
    Titulo VARCHAR(70) NOT NULL,
    Descricao VARCHAR(70) NOT NULL,
    Data_Envio DATE NOT NULL,
    Publico_Alvo VARCHAR(70) NOT NULL
);

CREATE TABLE PAREAMENTO(
    id SERIAL PRIMARY KEY,
    STATUS_PROJETO_id integer REFERENCES STATUS_PROJETO (id),
    GRUPO_id integer REFERENCES GRUPO (id),
    DEMANDA_id integer REFERENCES DEMANDA (id),
    Data DATE NOT NULL
);

CREATE TABLE DIFICULDADE(
    id SERIAL PRIMARY KEY,
    Descricao VARCHAR(20) CHECK (Descricao IN ('Básico','Intermediário','Difícil')) NOT NULL
);

CREATE TABLE AVALIACAO_DEMANDA(
    id SERIAL PRIMARY KEY,
    DEMANDA_id integer REFERENCES DEMANDA (id),
    COORDENADOR_id integer REFERENCES COORDENADOR (id),
    DIFICUDADE_id integer REFERENCES DIFICUDADE (id)
);