CREATE TABLE USUARIO(
    id SERIAL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL,
    Senha VARCHAR(300) NOT NULL,
    Telefone VARCHAR(70) NOT NULL,
    Tipo VARCHAR(20) CHECK (Tipo IN ('Aluno','Coordenador','Professor', 'Empreendedor')) NOT NULL
);

CREATE TABLE PROJETO(
    id SERIAL PRIMARY KEY,
    DOCENTE_id integer REFERENCES DOCENTE (id),
    PAREAMENTO_id integer REFERENCES PAREAMENTO (id),
    STATUS_PROJETO_id integer REFERENCES STATUS_PROJETO (id),
    GRUPO_id integer REFERENCES GRUPO (id),
    DEMANDA_id integer REFERENCES DEMANDA (id),
    Titulo VARCHAR(70) NOT NULL,
    Descricao VARCHAR(70) NOT NULL,
    Prazo VARCHAR(70) NOT NULL,
    Tipo VARCHAR(70) NOT NULL
);

CREATE TABLE EMPREENDEDOR(
    id SERIAL PRIMARY KEY,
    USUARIO_id integer REFERENCES USUARIO (id),
    Nome VARCHAR(70) NOT NULL,
    Setor VARCHAR(70) NOT NULL,
    CNPJ CHAR(14) NOT NULL
);

CREATE TABLE COORDENADOR(
    id SERIAL PRIMARY KEY,
    USUARIO_id integer REFERENCES USUARIO (id),
    Nome VARCHAR(70) NOT NULL,
);

CREATE TABLE STATUS_AVALIACAO(
    id SERIAL PRIMARY KEY,
    Descricao VARCHAR(70) NOT NULL,
);

CREATE TABLE DEMANDA(
    id SERIAL PRIMARY KEY,
    STATUS_AVALIACAO_id integer REFERENCES STATUS_AVALIACAO (id),
    EMPREENDEDOR_id integer REFERENCES EMPREENDEDOR (id),
    Titulo VARCHAR(70) NOT NULL,
    Descricao VARCHAR(70) NOT NULL,
    Data_Envio DATE NOT NULL,
    Publico_Alvo VARCHAR(70) NOT NULL,
);

CREATE TABLE DIFICULDADE(
    id SERIAL PRIMARY KEY,
    Descricao VARCHAR(20) CHECK (Descricao IN ('Básico','Intermediário','Difícil')) NOT NULL,
);

CREATE TABLE AVALIACAO_DEMANDA(
    id SERIAL PRIMARY KEY,
    DEMANDA_id integer REFERENCES DEMANDA (id),
    COORDENADOR_id integer REFERENCES COORDENADOR (id),
    DIFICUDADE_id integer REFERENCES DIFICUDADE (id),
);